image: node:14.15.0

pipelines:
    default:
        - step:
              name: Jest Unit Tests
              caches:
                  - node
              services:
                  - mongo
              script:
                  - npm run decrypt -- local.settings.enc local.settings.json
                  - npm install
                  - npm test
    branches:
        "{STS-**,admin,andrey,ilya,justin,valeriy,vlad}":
            - step:
                  name: ESLint
                  caches:
                      - node
                  script:
                      - npm install eslint
                      - npx eslint .

definitions:
    services:
        mongo:
            image: mongo
        postgres:
            image: postgres
