image: node:14.15.0

pipelines:
    branches:
        "{master,staging,dev}":
            - parallel:
                  - step:
                        name: Jest Unit Tests
                        caches:
                            - node
                        script:
                            - npm run decrypt -- local.settings.enc local.settings.json
                            - npm install
                            - npm test
                  - step:
                        name: ESLint
                        script:
                            - npm install eslint
                            - npx eslint .
                        caches:
                            - node
