image: node:14.15.0

definitions:
    services:
        mongo:
            image: mongo
        postgres:
            image: postgres
    steps:
        - step: &jest-test
              name: Jest Unit Tests
              caches:
                  - node
              services:
                  - mongo
              script:
                  - npm run decrypt -- local.settings.enc local.settings.json
                  - npm install
                  - npm test
        - step: &lint-test
              name: ESLint
              caches:
                  - node
              script:
                  - npm install eslint
                  - npx eslint .

pipelines:
    default:
        - step: *jest-test

    branches:
        "{STS-**,admin,andrey,ilya,justin,valeriy,vlad}":
            - parallel:
                  - step: *lint-test
                  - step: *jest-test
