openapi: 3.0.0
info:
  version: 0.0.1
  title: Trukt
  description: Transportation management system
  license:
    name: Private
    url: there is no url
servers:
  - url: 'https://truktbackend-dev.rcgauto.p.azurewebsites.net'
    description: Development server
  - url: 'https://truktbackend-staging.rcgauto.p.azurewebsites.net'
    description: Staging server
  - url: 'https://truktbackend.rcgauto.p.azurewebsites.net'
    description: Production server
paths:
  /attachments:
    post:
      $ref: paths\attachments\post.yaml
    get:
      $ref: paths\attachments\get.yaml
    delete:
      $ref: paths\attachments\delete.yaml
    patch: 
      $ref: paths\attachments\patch.yaml
  /edi/204/inbound:
    $ref: paths\edi@204@inbound.yaml
  /edi/214/inbound:
    $ref: paths\edi@214@inbound.yaml
  /edi/214/outbound:
    $ref: paths\edi@214@outbound.yaml
  /edi/990/outbound/accept:
    $ref: paths\edi@990@outbound@accept.yaml
  /edi/990/outbound/reject:
    $ref: paths\edi@990@outbound@reject.yaml