openapi: 3.0.0
info:
  version: 0.0.1
  title: Trukt
  description: Transportation management system
servers:
  - url: 'https://truktbackend-dev.rcgauto.p.azurewebsites.net'
    description: Development server
  - url: 'https://truktbackend-staging.rcgauto.p.azurewebsites.net'
    description: Staging server
  - url: 'https://truktbackend.rcgauto.p.azurewebsites.net'
    description: Production server
paths:
  /attachments:
    post:
      $ref: paths\attachments\post.yaml
  /attachments/search:
    get:
      $ref: paths\attachments\search.yaml
  /attachments/{guid}:
    get:
      $ref: paths\attachments\get.yaml
    delete:
      $ref: paths\attachments\delete.yaml
    patch:
      $ref: paths\attachments\patch.yaml
  /edi/204/inbound:
    $ref: paths\edi\204\inbound.yaml
  /edi/214/inbound:
    $ref: paths\edi\214\inbound.yaml
  /edi/214/outbound:
    $ref: paths\edi\214\outbound.yaml
  /edi/990/outbound/accept:
    $ref: paths\edi\990\outbound_accept.yaml
  /edi/990/outbound/reject:
    $ref: paths\edi\990\outbound_reject.yaml
  /order:
    post:
      $ref: paths\order\post.yaml
  /order/getorders:
    post:
      $ref: paths\order\search.yaml
  /order/{guid}:
    get:
      $ref: paths\order\get.yaml
  /picklist/options:
    get:
      $ref: paths\picklist\get.yaml
  /statusmanager/{guid}:
    get:
      $ref: paths\statusmanager\get.yaml
  /statusmanager/{guid}/{jobGuid}:
    get:
      $ref: paths\statusmanager\jobGuid\get.yaml
  /terminal:
    get:
      $ref: paths\terminal\search.yaml
  /terminal/{terminalGuid}:
    get:
      $ref: paths\terminal\get.yaml
  /variables/{name}:
    get:
      $ref: paths\variable\get.yaml
  /variable:
    post:
      $ref: paths\variable\post.yaml
  /pubsub/token:
    get:
      $ref: paths\pubsub\get.yaml
  /loadboard/{jobId}:
    put:
      $ref: paths\loadboard\put.yaml
    get:
      $ref: paths\loadboard\get.yaml
    delete:
      $ref: paths\loadboard\delete.yaml
    post:
      $ref: paths\loadboard\post.yaml
  /invoice/{invoiceId}:
    get:
      $ref: paths\invoice\get.yaml
  /invoice:
    post:
      $ref: paths\invoice\post.yaml
  /index/order/number:
    get:
      $ref: paths\index\order\get.yaml
  /index/job/number:
    get:
      $ref: paths\index\job\get.yaml
  /expense/{expenseId}:
    get:
      $ref: paths\expense\expenseId\get.yaml
    patch:
      $ref: paths\expense\expenseId\patch.yaml
  /expense:
    post:
      $ref: paths\expense\post.yaml
    patch:
      $ref: paths\expense\patch.yaml
  /bill/{billId}:
    get:
      $ref: paths\bill\get.yaml
  /bill:
    post:
      $ref: paths\bill\post.yaml
  /account/{accountType}:
    get:
      $ref: paths\account\search.yaml
  /account/{accountType}/{accountId}:
    get:
      $ref: paths\account\get.yaml
