openapi: 3.0.0
info:
  version: 0.0.2
  title: Trukt
  description: Transportation management system
servers:
  - url: 'https://truktapi-dev.rcgauto.net'
    description: Development server
  - url: 'https://truktapi-staging.rcgauto.net'
    description: Staging server
  - url: 'https://truktapi.rcgauto.net'
    description: Production server
paths:
  /attachments:
    post:
      $ref: paths/attachments/post.yaml
  /attachments/search:
    get:
      $ref: paths/attachments/search.yaml
  /attachments/{guid}:
    get:
      $ref: paths/attachments/get.yaml
    delete:
      $ref: paths/attachments/delete.yaml
    patch:
      $ref: paths/attachments/patch.yaml
  /edi/204/inbound:
    $ref: paths/edi/204/inbound.yaml
  /edi/214/inbound:
    $ref: paths/edi/214/inbound.yaml
  /edi/214/outbound:
    $ref: paths/edi/214/outbound.yaml
  /edi/990/outbound/accept:
    $ref: paths/edi/990/outbound_accept.yaml
  /edi/990/outbound/reject:
    $ref: paths/edi/990/outbound_reject.yaml
  /order:
    post:
      $ref: paths/order/post.yaml
    patch:
      $ref: paths/order/patch.yaml
  /order/getorders:
    post:
      $ref: paths/order/search.yaml
  /order/{guid}:
    get:
      $ref: paths/order/get.yaml
    delete:
      $ref: paths/order/deleteOrder.yaml
  /order/find_by_vin/{vin}:
    get:
      $ref: paths/order/findByVin.yaml
  /order/{orderGuid}/tender/accept:
    put:
      $ref: paths/order/putTenderAccept.yaml
  /order/tender/accept:
    put:
      $ref: paths/order/putTendersAccept.yaml
  /order/{orderGuid}/tender/reject:
    put:
      $ref: paths/order/putTenderReject.yaml
  /order/tender/reject:
    put:
      $ref: paths/order/putTendersReject.yaml
  /order/{orderGuid}/notes:
    get:
      $ref: paths/order/getNotes.yaml
  /order/{orderGuid}/notes/all:
    get:
      $ref: paths/order/getAllNotes.yaml
  /order/{orderGuid}/clientNote:
    put:
      $ref: paths/order/putClientNote.yaml
  /order/{orderGuid}/invoices:
    get:
      $ref: paths/order/getOrderInvoice.yaml
  /job/{jobGuid}/notes:
    get:
      $ref: paths/job/getNotes.yaml
  /job/{jobGuid}/bills:
    get:
      $ref: paths/job/getBills.yaml
  /job/{jobGuid}/hold:
    post:
      $ref: paths/job/addHold.yaml
    delete:
      $ref: paths/job/removeHold.yaml
  /job/{jobGuid}/ready:
    put:
      $ref: paths/job/setToReady.yaml
  /job/{jobGuid}/complete:
    put:
      $ref: paths/job/setToComplete.yaml
  /job/{jobGuid}/uncomplete:
    put:
      $ref: paths/job/setToUncomplete.yaml
  /order/{orderGuid}/hold:
    put:
      $ref: paths/order/markOnHold.yaml
  /order/{orderGuid}/unhold:
    put:
      $ref: paths/order/removeHold.yaml
  /order/{orderGuid}/complete:
    put:
      $ref: paths/order/markComplete.yaml
  /order/{orderGuid}/uncomplete:
    put:
      $ref: paths/order/markUncomplete.yaml
  /order/{orderGuid}/undelete:
    put:
      $ref: paths/order/undeleteOrder.yaml
  /order/{orderGuid}/delivered:
    put:
      $ref: paths/order/markDelivered.yaml
  /order/{orderGuid}/undelivered:
    put:
      $ref: paths/order/markUndelivered.yaml
  /order/{orderGuid}/cancel:
    put:
      $ref: paths/order/cancelOrder.yaml
  /order/{orderGuid}/uncancel:
    put:
      $ref: paths/order/uncancelOrder.yaml
  /picklist/options:
    get:
      $ref: paths/picklist/get.yaml
  /statusmanager/{guid}:
    get:
      $ref: paths/statusmanager/get.yaml
  /statusmanager/{guid}/{jobGuid}:
    get:
      $ref: paths/statusmanager/jobGuid/get.yaml
  /terminal:
    get:
      $ref: paths/terminal/search.yaml
  /terminal/{terminalGuid}:
    get:
      $ref: paths/terminal/get.yaml
  /variables/{name}:
    get:
      $ref: paths/variable/get.yaml
  /variable:
    post:
      $ref: paths/variable/post.yaml
  /pubsub/token:
    get:
      $ref: paths/pubsub/get.yaml
  /loadboard/{jobId}:
    put:
      $ref: paths/loadboard/put.yaml
    get:
      $ref: paths/loadboard/get.yaml
    delete:
      $ref: paths/loadboard/delete.yaml
    post:
      $ref: paths/loadboard/post.yaml
  /loadboard/{jobId}/dispatch:
    post:
      $ref: paths/loadboard/dispatch/post.yaml
    put:
      $ref: paths/loadboard/dispatch/put.yaml
  /loadboard/{jobId}/accept:
    put:
      $ref: paths/loadboard/dispatch/accept.yaml
  /invoice/{invoiceGuid}:
    get:
      $ref: paths/invoice/get.yaml
  /invoice/link/{line1Guid}/{line2Guid}:
    put:
      $ref: paths/invoice/linkLine.yaml
    delete:
      $ref: paths/invoice/unlinkLine.yaml
  /bill/{billGuid}:
    get:
      $ref: paths/bill/get.yaml
  /bill/{billGuid}/line:
    post:
      $ref: paths/bill/addBillLine.yaml
  /bill/{billGuid}/lines:
    delete:
      $ref: paths/bill/deleteBillLines.yaml
  /bill/{billGuid}/line/{lineGuid}:
    put:
      $ref: paths/bill/updateBillLine.yaml
    delete:
      $ref: paths/bill/deleteBillLine.yaml
  /invoice/order/{orderGuid}:
    get:
      $ref: paths/invoice/getOrderInvoices.yaml
  /invoice/job/{jobGuid}:
    get:
      $ref: paths/invoice/getJobInvoices.yaml
  /invoice/{invoiceGuid}/line:
    post:
      $ref: paths/invoice/addInvoiceLine.yaml
  /invoice/{invoiceGuid}/lines:
    delete:
      $ref: paths/invoice/deleteInvoiceLines.yaml
  /invoice/{invoiceGuid}/line/{lineGuid}:
    put:
      $ref: paths/invoice/updateInvoiceLine.yaml
    delete:
      $ref: paths/invoice/deleteInvoiceLine.yaml
  /index/order/number:
    get:
      $ref: paths/index/order/get.yaml
  /index/job/number:
    get:
      $ref: paths/index/job/get.yaml
  /expense/{expenseId}:
    get:
      $ref: paths/expense/expenseId/get.yaml
    patch:
      $ref: paths/expense/expenseId/patch.yaml
    delete:
      $ref: paths/expense/expenseId/delete.yaml
  /expense:
    post:
      $ref: paths/expense/post.yaml
    patch:
      $ref: paths/expense/patch.yaml
  /expense/search:
    get:
      $ref: paths/expense/search.yaml
  /account/{accountType}:
    get:
      $ref: paths/account/search.yaml
  /account/{accountType}/{accountId}:
    get:
      $ref: paths/account/get.yaml
  /user/{userRole}/search:
    get:
      $ref: paths/user/search.yaml
  /loadboard/requests/job/{jobGuid}:
    get:
      $ref: paths/loadboard/requests/get.yaml
  /loadboard/requests/create:
    post:
      $ref: paths/loadboard/requests/create.yaml
  /loadboard/requests/cancel:
    post:
      $ref: paths/loadboard/requests/cancel.yaml
  /loadboard/requests/{requestGuid}/accept:
    put:
      $ref: paths/loadboard/requests/accept.yaml
  /loadboard/requests/{requestGuid}/decline:
    put:
      $ref: paths/loadboard/requests/decline.yaml
  /loadboard/posting/booked:
    post:
      $ref: paths/loadboard/dispatch/booked.yaml
  /note/{object}/{objectGuid}:
    post:
      $ref: paths/notes/post.yaml
  /note/{noteGuid}:
    put:
      $ref: paths/notes/put.yaml
    delete:
      $ref: paths/notes/delete.yaml
  /invoice/order/{orderGuid}/export:
    put:
      $ref: paths/invoice/export.yaml
  /bill/order/{orderGuid}/export:
    put:
      $ref: paths/bill/export.yaml
  /job/{jobGuid}/stop/{stopGuid}/status/{status}:
    put:
      $ref: paths/job/updateStopStatus.yaml
  /job/statuses:
    get:
      $ref: paths/job/getStatuses.yaml
  /bulk/order/users:
    put:
      $ref: paths/bulk/updateOrderUsers.yaml
  /bulk/tender/accept:
    put:
      $ref: paths/bulk/putAcceptLoadTenders.yaml
  /bulk/tender/reject:
    put:
      $ref: paths/bulk/putRejectLoadTenders.yaml
  /bulk/job/users:
    put:
      $ref: paths/bulk/updateJobUsers.yaml
  /bulk/job/dates:
    put:
      $ref: paths/bulk/updateJobDates.yaml
  /bulk/job/status:
    put:
      $ref: paths/bulk/updateJobStatus.yaml
  /bulk/job/prices:
    put:
      $ref: paths/bulk/updateJobPrices.yaml
  /bulk/job/status/ready:
    put:
      $ref: paths/bulk/setJobReady.yaml
  /job/{jobGuid}/dispatch/carrier:
    get:
      $ref: paths/job/getCarrier.yaml
  /job/{jobGuid}:
    delete:
      $ref: paths/job/delete.yaml
  /job/{jobGuid}/undelete:
    put:
      $ref: paths/job/undelete.yaml
  /job/{jobGuid}/cancel:
    put:
      $ref: paths/job/cancel.yaml
  /job/{jobGuid}/uncancel:
    put:
      $ref: paths/job/uncancel.yaml
  /job/{jobGuid}/deliver:
    put:
      $ref: paths/job/deliver.yaml
  /job/{jobGuid}/undeliver:
    put:
      $ref: paths/job/undeliver.yaml
  /bulk/order/bill/export:
    put:
      $ref: paths/bulk/exportOrderBill.yaml
  /bulk/order/invoice/export:
    put:
      $ref: paths/bulk/exportOrderInvoice.yaml