
exports.up = function (knex)
{
    return knex
        .raw(`
        CREATE OR REPLACE VIEW salesforce.accounts AS
        SELECT
            accountnumber as account_number,
            accountsource as account_source,
            active__c as active,
            auction_id__c as auction_id,
            auto_insurance_expiration__c as auto_insurance_expiration,
            autoims_client_id__c as autoims_client_id,
            azure_id__c as azure_id,
            bank_account_name__c as bank_account_name,
            bank_account_number__c as bank_account_number,
            bank_account_type__c as bank_account_type,
            bank_routing_number__c as bank_routing_number,
            billingcity as billing_city,
            billingcountry as billing_country,
            billinggeocodeaccuracy as billing_geocode_accuracy,
            billinglatitude as billing_latitude,
            billinglongitude as billing_longitude,
            billingpostalcode as billing_postal_code,
            billingstate as billing_state,
            billingstreet as billing_street,
            blacklist__c as blacklist,
            brokerauthority__c as broker_authority,
            business_type__c as business_type,
            cargo_insurance_expiration__c as cargo_insurance_expiration,
            carrier_type__c as carrier_type,
            cell_phone__c as cell_phone,
            certificate_holder__c as certificate_holder,
            client_account_manager__c as client_account_manager,
            coi_request_date__c as coi_request_date,
            commonauthority__c as common_authority,
            contractauthority__c as contract_authority,
            counterparty_guid__c as counter_party_guid,
            createdbyid as created_by_id,
            createddate as created_date,
            credit_limit_amount__c as credit_limit_amount,
            customer_in_qbo__c as customer_in_qbo,
            customer_priority__c as customer_priority,
            dat_username__c as dat_username,
            dba_name__c as dba_name,
            delivery_notes__c as delivery_notes,
            description as description,
            dot_number__c as dot_number,
            dot_number_status__c as dot_number_status,
            email__c as email,
            emergency_phone__c as emergency_phone,
            factoring_company__c as factoring_company,
            fax as fax,
            firstname as first_name,
            flag__c as flag,
            flag_history__c as flag_history,
            fraud_identity_theft_status__c as fraud_identity_theft_status,
            free_phone__c as free_phone,
            guid__c as guid,
            icp_eligible__c as icp_eligible,
            icp_gp__c as icp_gp,
            icp_multiplier__c as icp_multiplier,
            id as id,
            inactive__c as inactive,
            industry as industry,
            insurance_expiration__c as insurance_expiration,
            insurance_on_file__c as insurance_on_file,
            internal_notes__c as internal_notes,
            iscustomerportal as is_customer_portal,
            isdeleted as is_deleted,
            ispartner as is_partner,
            ispersonaccount as is_person_account,
            is_synced_in_super as is_synced_in_super,
            job_title__c as job_title,
            lastmodifieddate as last_modified_date,
            lastname as last_name,
            lastreferenceddate as last_referenced_date,
            lastvieweddate as last_viewed_date,
            liability_insurance_expiration__c as liability_insurance_expiration,
            lkq_training_items__pc as lkq_training_items,
            loadboard_instructions__c as loadboard_instructions,
            masterrecord__guid__c as master_record_guid,
            masterrecordid as master_record_id,
            mc_number__c as mc_number,
            name as name,
            notes__c as notes,
            number_of_locations__c as number_of_locations,
            numberofemployees as number_of_employees,
            operations_email__c as operations_email,
            order_instructions__c as order_instructions,
            ownerid as owner_id,
            parentid as parent_id,
            payment_method__c as payment_method,
            payment_terms__c as payment_terms,
            pending_cancellation_date__c as pending_cancellation_date,
            personassistantname as person_assistant_name,
            personassistantphone as person_assistant_phone,
            personbirthdate as person_birth_date,
            personcontactid as person_contact_id,
            persondepartment as person_department,
            personemail as person_email,
            personemailbounceddate as person_email_bounced_date,
            personemailbouncedreason as person_email_bounced_reason,
            personhomephone as person_home_phone,
            personindividualid as person_individual_id,
            personlastcurequestdate as person_last_cu_request_date,
            personlastcuupdatedate as person_last_cu_update_date,
            personleadsource as person_lead_source,
            personmailingcity as person_mailing_city,
            personmailingcountry as person_mailing_country,
            personmailinggeocodeaccuracy as person_mailing_geocode_accuracy,
            personmailinglatitude as person_mailing_latitude,
            personmailinglongitude as person_mailing_longitude,
            personmailingpostalcode as person_mailing_postal_code,
            personmailingstate as person_mailing_state,
            personmailingstreet as person_mailing_street,
            personmobilephone as person_mobile_phone,
            personothercity as person_other_city,
            personothercountry as person_other_country,
            personothergeocodeaccuracy as person_other_geocode_accuracy,
            personotherlatitude as person_other_latitude,
            personotherlongitude as person_other_longitude,
            personotherphone as person_other_phone,
            personotherpostalcode as person_other_postal_code,
            personotherstate as person_other_state,
            personotherstreet as person_other_street,
            persontitle as person_title,
            phone as phone_number,
            photourl as photo_url,
            pickup_notes__c as pickup_notes,
            portfolio_code__c as portfolio_code,
            preferred__c as preferred,
            primary_contact__c as primary_contact_id,
            primary_contact__pc as primary_contact_person_id,
            qb_id__c as qb_id,
            rating as rating,
            recordtypeid as record_type_id,
            referral_amount__c as referral_amount,
            referral_code__c as referral_code,
            requiresattention__c as requires_attention,
            sales_account_manager__c as sales_account_manager,
            salutation as salutation,
            sd_guid__pc as sd_guid,
            search_address__c as search_address,
            sfid as sf_id,
            shippingcity as shipping_city,
            shippingcountry as shipping_country,
            shippinggeocodeaccuracy as shipping_geocode_accuracy,
            shippinglatitude as shipping_latitude,
            shippinglongitude as shipping_longitude,
            shippingpostalcode as shipping_postal_code,
            shippingstate as shipping_state,
            shippingstreet as shipping_street,
            sic as sic,
            sicdesc as sic_desc,
            site as site,
            sla__c as sla,
            sla_days__c as sla_days,
            sla_expiration_date__c as sla_expiration_date,
            sla_serial_number__c as sla_serial_number,
            status__c as status,
            sub_industry__c as sub_industry,
            suite__c as suite,
            systemmodstamp as system_mod_stamp,
            tax_id__c as tax_id,
            track_1099__c as track1099,
            trainee__c as trainee,
            trainer__c as trainer,
            training_date__c as training_date,
            training_items__c as training_items,
            truckstop_username__c as truckstop_username,
            type as type,
            upsell_opportunity__c as upsell_opportunity,
            user_role__c as user_role,
            uses_factoring_company__c as uses_factoring_company,
            vendor_type__c as vendor_type,
            website as website
        FROM salesforce.account;
    
        CREATE OR REPLACE VIEW salesforce.contacts AS
        SELECT
            accountid as account_id,
            accounting_contact__c as accounting_contact,
            assistantname as assistant_name,
            assistantphone as assistant_phone,
            birthdate as birth_date,
            createddate as created_date,
            department as department,
            description as description,
            email as email,
            emailbounceddate as email_bounced_date,
            emailbouncedreason as email_bounced_reason,
            fax as fax,
            firstname as first_name,
            guid__c as guid,
            homephone as home_phone,
            id as id,
            individualid as individual_id,
            isdeleted as is_deleted,
            isemailbounced as is_email_bounced,
            ispersonaccount as is_person_account,
            lastname as last_name,
            leadsource as lead_source,
            lkq_training_items__c as lkq_training_items,
            mailingcity as mailing_city,
            mailingcountry as mailing_country,
            mailinggeocodeaccuracy as mailing_geocode_accuracy,
            mailinglatitude as mailing_latitude,
            mailinglongitude as mailing_longitude,
            mailingpostalcode as mailing_postal_code,
            mailingstate as mailing_state,
            mailingstreet as mailing_street,
            mobilephone as mobile_number,
            name as name,
            othercity as other_city,
            othercountry as other_country,
            othergeocodeaccuracy as other_geocode_accuracy,
            otherlatitude as other_latitude,
            otherlongitude as other_longitude,
            otherphone as other_phone,
            otherpostalcode as other_postal_code,
            otherstate as other_state,
            otherstreet as other_street,
            phone as phone_number,
            photourl as photo_url,
            recordtypeid as record_type_id,
            salutation as salutation,
            sd_guid__c as sd_guid,
            sfid as sf_id,
            systemmodstamp as system_mod_stamp,
            title as title,
            trainer__c as trainer,
            training_date__c as training_date,
            training_items__c as training_items,
            primary_contact__c as primary_contact
        FROM salesforce.contact;

        CREATE OR REPLACE VIEW salesforce.record_types AS
        SELECT
            createddate as created_date,
            name as name,
            systemmodstamp as system_mod_stamp,
            isactive as is_active,
            description as description,
            sfid as sf_id,
            id as id,
            sobjecttype as object_type
        FROM salesforce.recordtype;
    `);
};

exports.down = function (knex)
{
    return knex.raw(`
        DROP VIEW IF EXISTS salesforce.accounts;
        DROP VIEW IF EXISTS salesforce.contacts;
        DROP VIEW IF EXISTS salesforce.record_types;
    `);
};
